# Generated by Django 2.2.5 on 2019-09-09 10:14

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=7)),
                ('image_de_CIN', models.ImageField(upload_to=core.models.user_directory_path)),
                ('nom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('', ''), ('Homme', 'Homme'), ('Femme', 'Femme')], max_length=5)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=10)),
                ('date_de_RDV', models.DateTimeField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_de_RDV'],
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
