# Generated by Django 2.2.5 on 2019-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=7)),
                ('nom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('', ''), ('Homme', 'Homme'), ('Femme', 'Femme')], max_length=5)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=10)),
                ('date_de_RDV', models.DateTimeField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_de_RDV'],
            },
        ),
    ]
