# Generated by Django 2.2.5 on 2019-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='sexe',
            field=models.CharField(choices=[('', ''), ('Homme', 'Homme'), ('Femme', 'Femme')], max_length=5),
        ),
    ]
